POST http://localhost:3000/recipes
content-type: application/json

{
  "name": "pinaattilätyt",
  "method": "Sekoita ainekset keskenään ja anna turvota 30 min. Paista pannulla ja tarjoile esim. marjojen kanssa.",
  "servings": 12
}